
- hosts: webs
  vars:
    ansible_user: vagrant
    directorioNgix: /usr/share/nginx/html/app
    ngixUser: www-data
  tasks:
    - name: Crear usuario de prueba
      user:
        name: prueba
        password: 111
        become: yes

    - name: Instalar ngix
      apt:
        pkg=ngix
        state=latest
      become: yes
    - name: Asegurarse que ngix funciona
      service:
        name=ngix
        state=started
        enabled=yes
      become: yes #sudo
    - name: Crear el directorio /usr/share/nginx/html/app
      file:
        path: "{{directorioNgix}}"
        state: directory
        owner: "{{ngixUser}}"
        group: "{{ngixUser}}"
        mode: 0755
    - name: Copiar html app
      copy:
        src: ../ejemplo.html
        dest: "{{directorioNgix}}"
        owner: "{{ngixUser}}"
        group: "{{ngixUser}}"
        mode: 0755
