
- hosts: webs
  vars:
    
    remote_user: root
  tasks:
    - name: Instalar apache
      apt:
        pkg=apache2
        state=absent
        state=latest
        purge=true
      become: yes
    - name: Asegurarse que apache funciona
      service:
        name=apache2
        state=started
        enabled=yes
      become: yes

